---
# Can anyone tell me why the pods network is /16 and
# the service network is /12 in the official kube docs?
# Its madness!!! there are way more pods then services in a cluster!
# We will do a /16 for each
pod_subnet: 10.244.0.0/16
service_subnet: 10.245.0.0/16
service_ip: "10.245.0.1"       # This should be the first Usable IP Address in the service CIDR

cluster_name: dev.cluster.local
k8s_version: v1.30.0

api_version: kubeadm.k8s.io/v1beta3
cri_socket: unix:///run/containerd/containerd.sock
control_plane_endpoint_ip: 10.50.50.80
control_plane_endpoint_port: "6443"
api_endpoint_cert_names:
  # localhost
  - "127.0.0.1"
  - "::1"

  # Kubernetes API service IP
  - "{{ service_ip }}"

  # Load balancer/API endpoint
  - "{{ control_plane_endpoint_ip }}"
  - "api.{{ cluster_name }}"

  # Control plane nodes
  - "control-01.{{ cluster_name }}"
  - "control-02.{{ cluster_name }}"
  - "control-03.{{ cluster_name }}"
  - "10.50.50.81"
  - "10.50.50.82"
  - "10.50.50.83"

  # Internal kubernetes service names
  - "kubernetes"
  - "kubernetes.default"
  - "kubernetes.default.svc"
  - "kubernetes.default.svc.{{ cluster_name }}"
