---
- name: Download containerd
  block:
    - name: Create /tmp/nerdctl directory
      ansible.builtin.file:
        path: /tmp/nerdctl
        state: directory

    - name: Download nerdctl checksum file
      ansible.builtin.get_url:
        url: "{{ containerd_info.nerdctl_checksum_url }}"
        dest: /tmp/nerdctl/sha256sum

    - name: Read checksum file
      ansible.builtin.slurp:
        src: /tmp/nerdctl/sha256sum
      register: sum_cont

    - name: Set nerdctl filename
      ansible.builtin.set_fact:
        nerdctl_filename: "{{ containerd_info.nerdctl_url | basename }}"

    - name: Download and verify nerdctl
      ansible.builtin.get_url:
        url: "{{ containerd_info.nerdctl_url }}"
        dest: /tmp/nerdctl/nerdctl.tar.gz
        checksum: "sha256:{{ ((sum_cont['content'] | b64decode).split('\n') | select('regex', nerdctl_filename) | first).split(' ')[0] }}"
        mode: '0644'

    - name: Extract nerdctl
      ansible.builtin.unarchive:
        src: /tmp/nerdctl/nerdctl.tar.gz
        dest: /tmp/nerdctl/
        remote_src: yes

    - name: Copy nerdctl to /usr/local/bin
      ansible.builtin.copy:
        src: /tmp/nerdctl/nerdctl
        dest: /usr/local/bin/
        remote_src: yes
        mode: '0755'
        owner: root
        group: root

    - name: remove /tmp/nerdctl directory
      ansible.builtin.file:
        path: /tmp/nerdctl
        state: absent

  rescue:
    - name: remove /tmp/nerdctl directory
      ansible.builtin.file:
        path: /tmp/nerdctl
        state: absent

    - name: Fail with error
      ansible.builtin.fail:
        msg: "Failed to download and verify containerd"
  tags:
    - containerd
