---
- name: Download runc
  block:
    - name: Create /tmp/runc directory
      ansible.builtin.file:
        path: /tmp/runc
        state: directory

    - name: Download runc checksum file
      ansible.builtin.get_url:
        url: "{{ containerd_info.runc_checksum_url }}"
        dest: /tmp/runc/sha256sum

    - name: Read checksum file
      ansible.builtin.slurp:
        src: /tmp/runc/sha256sum
      register: sum_cont

    - name: Set runc filename
      ansible.builtin.set_fact:
        runc_filename: "{{ containerd_info.runc_url | basename }}"

    - name: Download and verify runc
      ansible.builtin.get_url:
        url: "{{ containerd_info.runc_url }}"
        dest: /tmp/runc/runc
        checksum: "sha256:{{ ((sum_cont['content'] | b64decode).split('\n') | select('regex', runc_filename) | first).split(' ')[0] }}"
        mode: '0644'

    - name: Copy runc to /usr/local/bin
      ansible.builtin.copy:
        src: /tmp/runc/runc
        dest: /usr/local/bin/runc
        remote_src: yes
        mode: '0755'
        owner: root
        group: root

    - name: remove /tmp/runc directory
      ansible.builtin.file:
        path: /tmp/runc
        state: absent

  rescue:
    - name: remove /tmp/runc directory
      ansible.builtin.file:
        path: /tmp/runc
        state: absent

    - name: Fail with error
      ansible.builtin.fail:
        msg: "Failed to download and verify containerd"
  tags:
    - containerd
    - runc
