---
# - name: Check it ca cert exists
#   ansible.builtin.stat:
#     path: /etc/kubernetes/pki/ca.crt
#   register: cni_kube_pki
#   tags:
#    - primary_control_node
#    - kubeadm

# - name: template the kubeadm config file
#   ansible.builtin.template:
#     src: kubeadm-config.yaml.j2
#     dest: /root/kubeadm-config.yaml
#     owner: root
#     group: root
#     mode: '0644'
#   when: not cni_kube_pki.stat.exists
#   tags:
#    - primary_control_node
#    - kubeadm

# - name: bootstrap the primary control node using kubeadm
#   ansible.builtin.command: kubeadm init --config=/root/kubeadm-config.yaml --upload-certs
#   register: kubeadm_results
#   async: 3600    # 45 minutes (60 * 60 = 3600 seconds)
#   poll: 5        # poll every 5 seconds
#   when: not cni_kube_pki.stat.exists
#   tags:
#    - primary_control_node
#    - kubeadm

# - name: debug the primary control node using kubeadm
#   ansible.builtin.debug:
#     msg:
#       - "kubeadm init result: {{ kubeadm_results.stdout }}"
#       - "kubeadm init error: {{ kubeadm_results.stderr }}"
#   tags:
#    - primary_control_node
#    - kubeadm
